INSERT INTO PAISES (C_PAIS, NOMBRE_PAIS, CINES)
VALUES (88,'Kenia', 250);

INSERT INTO PAISES VALUES (77, 'Zimbabwe', 500);

DELETE FROM PAISES WHERE C_PAIS = 77;

INSERT INTO PAISES (C_PAIS, NOMBRE_PAIS)
SELECT C_PELI+40, FORMATO FROM PELICULAS;
SELECT * FROM PAISES;
SELECT * FROM ALQUILER;
SELECT * FROM SOCIOS;
SELECT * FROM PELICULAS;

-- 1A INSERTAR MIS DATOS COMO UN SOCIO NUEVO
INSERT INTO SOCIOS
VALUES (1017, 'sufi', 'auiti', null, 'buenavista 14', 925830916);
-- 1B INSERTAR UN ALQUILER DE UNA PELICULA QUE ME GUSTE
INSERT INTO ALQUILER
VALUES (1017, 6, '01/02/23', 1, 'N', 7.5);
-- 2A A�ADIR A LA TABLA PAISES LOS NOMBRES DE LOS SOCIOS COMO SI FUERAN PAISES
INSERT INTO PAISES (C_PAIS, NOMBRE_PAIS)
SELECT C_SOCIO+20 - 1000, NOMBRE FROM SOCIOS;

-- EXTRA A�ADIR FILAS A LA TABLA PAISES PARA CONSEGUIR 200 ENTRADAS
INSERT INTO PAISES (C_PAIS, NOMBRE_PAIS)
SELECT C_PELI + 18 + (31)*0,SUBSTR(TITULO, 0, 10) FROM PELICULAS;
INSERT INTO PAISES (C_PAIS, NOMBRE_PAIS)
SELECT C_PELI + 18 + (31)*1,SUBSTR(TITULO, 0, 10) FROM PELICULAS;
INSERT INTO PAISES (C_PAIS, NOMBRE_PAIS)
SELECT C_PELI + 18 + (31)*2,SUBSTR(TITULO, 0, 10) FROM PELICULAS;
INSERT INTO PAISES (C_PAIS, NOMBRE_PAIS)
SELECT C_PELI + 18 + (31)*3,SUBSTR(TITULO, 0, 10) FROM PELICULAS;
INSERT INTO PAISES (C_PAIS, NOMBRE_PAIS)
SELECT C_PELI + 18 + (31)*4,SUBSTR(TITULO, 0, 10) FROM PELICULAS;
INSERT INTO PAISES (C_PAIS, NOMBRE_PAIS)
SELECT C_PELI + 18 + (31)*5,SUBSTR(TITULO, 0, 10) FROM PELICULAS;

ROLLBACK;
-- COMMIT;


MERGE INTO ARTICULO
USING PROVEEDOR
ON (ARTICULO.C_PROVEE = PROVEEDOR.C_PROVEE)
WHEN MATCHED THEN
UPDATE SET ARTICULO.PROVINCIA = PROVEEDOR.PROVINCIA;

-- create atrticulo 2 IDART DESCRIP PRECIO STOCK PRECIO >= 5
CREATE VIEW articulo2
AS
SELECT IDART,DESCRIP,PRECIO,STOCK FROM ARTICULO WHERE PRECIO >= 5;

DROP VIEW ARTICULO2;