INSERT INTO PAISES (C_PAIS, NOMBRE_PAIS, CINES)
VALUES (88,'Kenia', 250);

INSERT INTO PAISES VALUES (77, 'Zimbabwe', 500);

DELETE FROM PAISES WHERE C_PAIS = 77;

SELECT * FROM PAISES;

-- 1A INSERTAR MIS DATOS COMO UN SOCIO NUEVO
INSERT INTO SOCIOS
VALUES (1017, 'sufi', 'auiti', null, 'buenavista 14', 925830916);
SELECT * FROM SOCIOS;
-- 1B INSERTAR UN ALQUILER DE UNA PELICULA QUE ME GUSTE
INSERT INTO ALQUILER
VALUES (1017, 6, '01/02/23', 1, 'N', 7.5);
SELECT * FROM ALQUILER;

ROLLBACK;
-- COMMIT;