SET SERVEROUTPUT ON
SET VERIFY OFF
ACCEPT var NUMBER PROMPT 'Dime algo';
DECLARE
linea BINARY_INTEGER := &var;
BEGIN
  SELECT NOMBRE FROM ESTACION WHERE NESTACION = (
    SELECT NESTACION FROM LE WHERE NLINEA = linea AND ORDEN = 
    (
      SELECT MIN(ORDEN) FROM LE WHERE NLINEA = linea
    )
  );
  DBMS_OUTPUT.PUT_LINE('Linea: '||linea);
END;
/
SET SERVEROUTPUT OFF
SET VERIFY ON