SET SERVEROUTPUT ON
SET VERIFY OFF
ACCEPT X PROMPT 'TECLEE UN Nº:'
DECLARE
	TYPE TREGISTRO IS RECORD(
		NUMERO BINARY_INTEGER,
		LETRA CHAR(2)
	);
	TYPE TVECTOR IS TABLE OF TREGISTRO INDEX BY BINARY_INTEGER;
	V TVECTOR;
	C VARCHAR2(50):='';
	INDICE BINARY_INTEGER;
	N NUMBER:=&X;
BEGIN	
	V(1).NUMERO:=1000;	V(1).LETRA:='M';		
	V(2).NUMERO:=900;	V(2).LETRA:='CM';		
	V(3).NUMERO:=500;	V(3).LETRA:='D';		
	V(4).NUMERO:=400;	V(4).LETRA:='CD';		
	V(5).NUMERO:=100;	V(5).LETRA:='C';		
	V(6).NUMERO:=90;	V(6).LETRA:='XC';		
	V(7).NUMERO:=50;	V(7).LETRA:='L';		
	V(8).NUMERO:=40;	V(8).LETRA:='XL';		
	V(9).NUMERO:=10;	V(9).LETRA:='X';		
	V(10).NUMERO:=9;	V(10).LETRA:='IX';		
	V(11).NUMERO:=5;	V(11).LETRA:='V';		
	V(12).NUMERO:=4;	V(12).LETRA:='IV';		
	V(13).NUMERO:=1;	V(13).LETRA:='I';		
	FOR I IN 1..13 LOOP
		WHILE N>=V(I).NUMERO LOOP
			C:=C||TRIM(V(I).LETRA);
			N:=N-V(I).NUMERO;			
		END LOOP;
	END LOOP;	
	DBMS_OUTPUT.PUT_LINE(C);
END;
/
SET SERVEROUTPUT OFF
SET VERIFY ON
