--1 TITULO DE LAS PELICULAS PRODUCIDAS EN AÑOS DIFERENTES A 2007
SELECT TITULO
FROM PELICULAS
WHERE ANNO = 2000;
--2 CUANTAS PELICULAS EN FORMATO DVD
SELECT COUNT(*)
FROM PELICULAS
WHERE FORMATO = 'DVD';
--3 LISTA LOS TITULOS Y LOS PRECIOS DE LAS PELICULAS
SELECT TITULO,
  PRECIO
FROM PELICULAS;
--4 PRECIO DE LA PELICULA MAS BARATA
SELECT MIN(PRECIO) FROM PELICULAS;
--5 DE QUE AÑO ES LA PELICULA MAS ANTIGUA
SELECT MIN(ANNO) FROM PELICULAS;
--6 CUANTAS PELICULAS ESTAN DE OFERTA
SELECT COUNT(*)
FROM PELICULAS
WHERE OFERTA = 'S';
--7 VISUALIZA LOS NOMBRES DE LOS PAISES QUE TIENEN MAS DE 500 CINES
SELECT NOMBRE_PAIS
FROM PAISES
WHERE CINES>500;
--8 TITULO DE LAS PELICULAS QUE ESTAN EN DVD
SELECT TITULO
FROM PELICULAS
WHERE FORMATO = 'DVD';
--9 EN QUE FECHA SE HIZO EL ULTIMO ALQUILER
SELECT MAX(FECHA) FROM ALQUILER;
--10 TITULO DE LAS PELICULAS QUE NO ESTAN EN DVD
SELECT TITULO
FROM PELICULAS
WHERE FORMATO != 'DVD';
--11 PRECIO MEDIO DE LAS PELICULAS
SELECT AVG(PRECIO) FROM PELICULAS;
--12 FECHA DEL ÚLTIMO ALQUILER
SELECT MAX(FECHA) FROM ALQUILER;
--13 AÑO DE LA PELÍCULA MÁS ANTIGUA QUE ESTÁ EN OFERTA
SELECT MAX(ANNO)
FROM PELICULAS
WHERE OFERTA='S';
--14 TITULO DE LAS PELICULSA EN MP4 POSTERIORES A 2008
SELECT TITULO
FROM PELICULAS
WHERE FORMATO='MP4'
AND ANNO     > 2008;
--15 NOMBRE DE LOS SOCIOS QUE PRESUMIBLEMENTE SON CHICAS
SELECT NOMBRE
FROM SOCIOS
WHERE NOMBRE LIKE '%a';
--16 TITULOS DE LAS PELICULAS QUE SON SECUELA DE TORRENTE
SELECT TITULO
FROM PELICULAS
WHERE TITULO LIKE 'Torrente%';
--17 TITULO DE LAS PELICULAS QUE EMPIEZEN POR M
SELECT TITULO
FROM PELICULAS
WHERE TITULO LIKE 'M%';
--18 TITULO DE LAS PELICULAS QUE TENGAN MENOS DE 7 LETRAS
SELECT TITULO
FROM PELICULAS
WHERE LENGTH(TITULO) < 7;
--19 TITULO DE LAS PELICULAS QUE TENGAN SOLO UNA PALABRA
SELECT TITULO
FROM PELICULAS
WHERE TITULO NOT LIKE '% %';
--20 CUANTAS PELICULAS TIENEN UN NUMERO EN SU TITULO
SELECT COUNT(*)
FROM PELICULAS
WHERE TITULO LIKE '%0%'
OR TITULO LIKE '%1%'
OR TITULO LIKE '%2%'
OR TITULO LIKE '%3%'
OR TITULO LIKE '%4%'
OR TITULO LIKE '%5%'
OR TITULO LIKE '%6%'
OR TITULO LIKE '%7%'
OR TITULO LIKE '%8%'
OR TITULO LIKE '%9%';
--CLASE 09-12-2002
SELECT APE1,
  APE2,
  NOMBRE
FROM SOCIOS
ORDER BY APE1,
  APE2,
  NOMBRE;
SELECT SYSDATE,SIN(355/113/2) FROM DUAL;
SELECT TRUNC(SYSDATE - TO_DATE('17/12/2002'),2)||' DIAS' FROM DUAL;
--21 TITULO DE LA PELICULA MAS CARA
SELECT TITULO,
  PRECIO
FROM PELICULAS
WHERE PRECIO =
  (SELECT MAX(PRECIO) FROM PELICULAS
  );
--22 TITULO DE LA PELICULA MÁS ANTIGUA
SELECT TITULO,
  ANNO
FROM PELICULAS
WHERE ANNO =
  (SELECT MIN(ANNO) FROM PELICULAS
  );
--23 ¿CUAL ES EL PAÍS QUE MÁS CINES TIENE?
SELECT NOMBRE_PAIS
FROM PAISES
WHERE CINES =
  (SELECT MAX(CINES) FROM PAISES
  );
SELECT * FROM PAISES ORDER BY CINES; -- COMPROBAR RESULTADO
--24 VISUALIZA LOS DISTINTOS FORMATOS DE PELICULAS
SELECT DISTINCT FORMATO
FROM PELICULAS;
--25 VISUALIZA LOS TITULOS DE PELICULAS QUE NO ESTAN NI EN DVD NI EN MP4
SELECT TITULO,
  FORMATO
FROM PELICULAS
WHERE FORMATO NOT IN ('MP4', 'DVD');
--26 TITULO DE LAS PELICULAS ESPAÑOLAS
SELECT TITULO
FROM PELICULAS
WHERE C_PAIS =
  (SELECT C_PAIS FROM PAISES WHERE NOMBRE_PAIS = 'España'
  );
SELECT TITULO FROM PELICULAS WHERE C_PAIS = 1;
--27 NOMBRE DE LOS SOCIOS QUE NO HAN ALQUILADO NINGUNA PELICULA
SELECT NOMBRE,
  C_SOCIO
FROM SOCIOS
WHERE C_SOCIO NOT IN
  (SELECT C_SOCIO FROM ALQUILER
  );
--28 TITULO DE LAS PELICULAS QUE SE HAN ALQUILADO ALGUNA VEZ
SELECT TITULO
FROM PELICULAS
WHERE C_PELI IN
  (SELECT C_PELI FROM ALQUILER
  );
--29 ¿CUANTAS VECES HA ALQUILADO ROSA?
SELECT COUNT(*)
FROM ALQUILER
WHERE C_SOCIO =
  (SELECT C_SOCIO FROM SOCIOS WHERE NOMBRE = 'rosa'
  );
--30 ¿CUANTAS VECES SE HA ALQUILADO TORRENTE?
SELECT COUNT(*)
FROM ALQUILER
WHERE C_PELI IN
  (SELECT C_PELI FROM PELICULAS WHERE TITULO LIKE 'Torrente%'
  );
--31 NOMBRE DE LOS PAISES QUE NO HAN REALIZADO PELICULAS
SELECT NOMBRE_PAIS
FROM PAISES
WHERE C_PAIS NOT IN
  (SELECT C_PAIS FROM PELICULAS
  );
--32 NOMBRE DE LOS SOCIOS QUE VIVEN EN LA CALLE SOL
SELECT NOMBRE
FROM SOCIOS
WHERE UPPER(DIRECCION) LIKE 'SOL%';
-- USAR UPPER OR LOWER (CASE) CUANDO
--NO SABES SI LA CADENA ESTA EN MINUSCULAS O MAYUSCULAS
--33 NOMBRE DE LOS SOCIOS QUE HAN VISTO LA PELICULA 'Viven'
SELECT NOMBRE
FROM SOCIOS
WHERE C_SOCIO IN
  (SELECT C_SOCIO
  FROM ALQUILER
  WHERE C_PELI =
    (SELECT C_PELI FROM PELICULAS WHERE TITULO = 'Viven'
    )
  );
--34 NOMBRE DE LOS PAISES EN LOS QUE SE ALQUILAN PELICULAS
SELECT NOMBRE_PAIS,
  C_PAIS
FROM PAISES
WHERE C_PAIS IN
  (SELECT C_PAIS FROM PELICULAS WHERE C_PAIS IN
    (SELECT C_PAIS FROM ALQUILER
    )
  );
--35 NOMBRE DE LOS SOCIOS QUE NO HAN VISTO TORRENTE
SELECT NOMBRE
FROM SOCIOS
WHERE C_SOCIO NOT IN
  (SELECT C_SOCIO
  FROM ALQUILER
  WHERE C_PELI IN
    (SELECT C_PELI FROM PELICULAS WHERE TITULO LIKE 'Torrente%'
    )
  );
--36 NOMBRE DE LOS SOCIOS QUE NO HAN ALQUILADO PELICULAS ESPAÑOLAS
SELECT NOMBRE
FROM SOCIOS
WHERE C_SOCIO NOT IN
  (SELECT C_SOCIO
  FROM ALQUILER
  WHERE C_PELI IN
    (SELECT C_PELI
    FROM PELICULAS
    WHERE C_PAIS IN
      (SELECT C_PAIS FROM PAISES WHERE NOMBRE_PAIS = 'España'
      )
    )
  );
--37 NOMBRE DE LOS SOCIOS QUE VEN PELICULAS QUE NO SON ESPAÑOLAS
SELECT NOMBRE
FROM SOCIOS
WHERE C_SOCIO IN
  (SELECT C_SOCIO
  FROM ALQUILER
  WHERE C_PELI IN
    (SELECT C_PELI
    FROM PELICULAS
    WHERE C_PAIS IN
      (SELECT C_PAIS FROM PAISES WHERE NOMBRE_PAIS != 'España'
      )
    )
  );
--38 VISUALIZA CUANTS PELICULAS SE HAN EREALIZADO EN LOS DISTINTOS AÑOS
SELECT ANNO,
  COUNT(C_PELI)
FROM PELICULAS
GROUP BY ANNO
ORDER BY ANNO;
--39 PRECIO MINIMO DE CADA FORMATO
SELECT FORMATO,
  MIN(PRECIO),
  COUNT(*)
FROM PELICULAS
GROUP BY FORMATO;
--40 VISUALIZA CUANTAS PELICULAS SE HAN ALQUILADO EN LOS DISTINTOS AÑOS
SELECT '20'
  ||SUBSTR(FECHA, 7, 2),
  COUNT(*)
FROM ALQUILER
GROUP BY '20'
  ||SUBSTR(FECHA, 7, 2);
--41 ¿CUANTOS ALQUILERES SE HICIERON EN MARZO DEL 2002?
SELECT COUNT(*)
FROM ALQUILER
WHERE FECHA LIKE '%03/02';
--42 ¿CUANTOS HERMANOS TIENE ROSA RODRIGUEZ NIETO?
SELECT COUNT(*)-1
FROM SOCIOS
WHERE APE1 = 'rodriguez'
AND APE2   = 'nieto';
--43 VISUALIZA LOS TITULOS DE LAS PELICULAS
--   JUNTO CON EL NOMBRE DEL PAIS QUE LAS HA REALIZADO
SELECT TITULO,
  NOMBRE_PAIS
FROM PELICULAS,
  PAISES
WHERE PELICULAS.C_PAIS = PAISES.C_PAIS;
--44 VISUALIZA UN LISTADO CON NOMBRE DE LOS SOCIOS JUNTO CON LOS CODIGOS
--   DE PELICULAS QUE HA ALQUILADO CADA UNO
SELECT NOMBRE,
  C_PELI
FROM SOCIOS,
  ALQUILER
WHERE SOCIOS.C_SOCIO = ALQUILER.C_SOCIO;
-- 45 VISUALIZA LOS TITULOS DE LAS PELIS JUNTO CON EL CODIGO DE LOS SOCIOS
--    QUE LA HAN ALQUILADO
SELECT TITULO,
  C_SOCIO
FROM PELICULAS,
  ALQUILER
WHERE PELICULAS.C_PELI = ALQUILER.C_PELI;
-- 46 VISUALIZA LOS NOMBRES DE LOS PAISES JUNTO CON EL TITULO DE SUS PELICULAS
--    QUE SE HAN ALQUILADO
SELECT DISTINCT NOMBRE_PAIS,
  TITULO
FROM PAISES,
  PELICULAS,
  ALQUILER
WHERE PAISES.C_PAIS  = PELICULAS.C_PAIS
AND PELICULAS.C_PELI = ALQUILER.C_PELI;
SELECT NOMBRE_PAIS,
  TITULO
FROM PAISES,
  PELICULAS
WHERE PAISES.C_PAIS   = PELICULAS.C_PAIS
AND PELICULAS.C_PELI IN
  (SELECT C_PELI FROM ALQUILER
  );
-- 47 VISUALIZA LOS NOMBRES DE LOS SOCIOS JUNTO CON EL TITULO DE LAS PELICULAS
--    QUE HA ALQUILADO CADA UNO
SELECT NOMBRE,
  TITULO
FROM SOCIOS,
  PELICULAS,
  ALQUILER
WHERE PELICULAS.C_PELI = ALQUILER.C_PELI
AND SOCIOS.C_SOCIO     = ALQUILER.C_SOCIO;
-- 48 ¿CUANTAS PELICULAS ESPAÑOLAS HA ALQUILADO ROSA?
SELECT COUNT(*)
FROM PELICULAS
WHERE C_PAIS =
  (SELECT C_PAIS FROM PAISES WHERE NOMBRE_PAIS = 'España'
  )
AND C_PELI IN
  (SELECT C_PELI
  FROM ALQUILER
  WHERE C_SOCIO =
    (SELECT C_SOCIO FROM SOCIOS WHERE NOMBRE = 'rosa'
    )
  );
-- 49 ¿CUANTOS DVDS FRANCESES HAY?
SELECT COUNT(*)
FROM PELICULAS
WHERE FORMATO = 'DVD'
AND C_PAIS    =
  (SELECT C_PAIS FROM PAISES WHERE NOMBRE_PAIS = 'Francia'
  );
-- 50 LISTADO CON LOS NOMBRES DE LOS PAISES JUNTO CON LOS AÑOS
--    EN QUE HAN REALIZADO PELICULAS
SELECT DISTINCT NOMBRE_PAIS,
  ANNO
FROM PAISES PA,
  PELICULAS PE
WHERE PA.C_PAIS = PE.C_PAIS ORDER BY NOMBRE_PAIS, ANNO;
--51 LISTADO CON TODOS LOS NOMBRES DE LOS PAISES JUNTO CON
--   EL NUMERO DE PELICULAS REALIZADAS
SELECT NOMBRE_PAIS, COUNT(*) FROM PAISES PA, PELICULAS PE
WHERE PA.C_PAIS = PE.C_PAIS GROUP BY NOMBRE_PAIS;