--1 TITULO DE LAS PELICULAS PRODUCIDAS EN Aï¿½OS DIFERENTES A 2007
SELECT TITULO
FROM PELICULAS
WHERE ANNO = 2000;
--2 CUANTAS PELICULAS EN FORMATO DVD
SELECT COUNT(*)
FROM PELICULAS
WHERE FORMATO = 'DVD';
--3 LISTA LOS TITULOS Y LOS PRECIOS DE LAS PELICULAS
SELECT TITULO,
  PRECIO
FROM PELICULAS;
--4 PRECIO DE LA PELICULA MAS BARATA
SELECT MIN(PRECIO) FROM PELICULAS;
--5 DE QUE Aï¿½O ES LA PELICULA MAS ANTIGUA
SELECT MIN(ANNO) FROM PELICULAS;
--6 CUANTAS PELICULAS ESTAN DE OFERTA
SELECT COUNT(*)
FROM PELICULAS
WHERE OFERTA = 'S';
--7 VISUALIZA LOS NOMBRES DE LOS PAISES QUE TIENEN MAS DE 500 CINES
SELECT NOMBRE_PAIS
FROM PAISES
WHERE CINES>500;
--8 TITULO DE LAS PELICULAS QUE ESTAN EN DVD
SELECT TITULO
FROM PELICULAS
WHERE FORMATO = 'DVD';
--9 EN QUE FECHA SE HIZO EL ULTIMO ALQUILER
SELECT MAX(FECHA) FROM ALQUILER;
--10 TITULO DE LAS PELICULAS QUE NO ESTAN EN DVD
SELECT TITULO
FROM PELICULAS
WHERE FORMATO != 'DVD';
--11 PRECIO MEDIO DE LAS PELICULAS
SELECT AVG(PRECIO) FROM PELICULAS;
--12 FECHA DEL ï¿½LTIMO ALQUILER
SELECT MAX(FECHA) FROM ALQUILER;
--13 Aï¿½O DE LA PELï¿½CULA Mï¿½S ANTIGUA QUE ESTï¿½ EN OFERTA
SELECT MAX(ANNO)
FROM PELICULAS
WHERE OFERTA='S';
--14 TITULO DE LAS PELICULSA EN MP4 POSTERIORES A 2008
SELECT TITULO
FROM PELICULAS
WHERE FORMATO='MP4'
AND ANNO     > 2008;
--15 NOMBRE DE LOS SOCIOS QUE PRESUMIBLEMENTE SON CHICAS
SELECT NOMBRE
FROM SOCIOS
WHERE NOMBRE LIKE '%a';
--16 TITULOS DE LAS PELICULAS QUE SON SECUELA DE TORRENTE
SELECT TITULO
FROM PELICULAS
WHERE TITULO LIKE 'Torrente%';
--17 TITULO DE LAS PELICULAS QUE EMPIEZEN POR M
SELECT TITULO
FROM PELICULAS
WHERE TITULO LIKE 'M%';
--18 TITULO DE LAS PELICULAS QUE TENGAN MENOS DE 7 LETRAS
SELECT TITULO
FROM PELICULAS
WHERE LENGTH(TITULO) < 7;
--19 TITULO DE LAS PELICULAS QUE TENGAN SOLO UNA PALABRA
SELECT TITULO
FROM PELICULAS
WHERE TITULO NOT LIKE '% %';
--20 CUANTAS PELICULAS TIENEN UN NUMERO EN SU TITULO
SELECT COUNT(*)
FROM PELICULAS
WHERE TITULO LIKE '%0%'
OR TITULO LIKE '%1%'
OR TITULO LIKE '%2%'
OR TITULO LIKE '%3%'
OR TITULO LIKE '%4%'
OR TITULO LIKE '%5%'
OR TITULO LIKE '%6%'
OR TITULO LIKE '%7%'
OR TITULO LIKE '%8%'
OR TITULO LIKE '%9%';
--CLASE 09-12-2002
SELECT APE1,
  APE2,
  NOMBRE
FROM SOCIOS
ORDER BY APE1,
  APE2,
  NOMBRE;
SELECT SYSDATE,SIN(355/113/2) FROM DUAL;
SELECT TRUNC(SYSDATE - TO_DATE('17/12/2002'),2)||' DIAS' FROM DUAL;
--21 TITULO DE LA PELICULA MAS CARA
SELECT TITULO,
  PRECIO
FROM PELICULAS
WHERE PRECIO =
  (SELECT MAX(PRECIO) FROM PELICULAS
  );
--22 TITULO DE LA PELICULA Mï¿½S ANTIGUA
SELECT TITULO,
  ANNO
FROM PELICULAS
WHERE ANNO =
  (SELECT MIN(ANNO) FROM PELICULAS
  );
--23 ï¿½CUAL ES EL PAï¿½S QUE Mï¿½S CINES TIENE?
SELECT NOMBRE_PAIS
FROM PAISES
WHERE CINES =
  (SELECT MAX(CINES) FROM PAISES
  );
SELECT * FROM PAISES ORDER BY CINES; -- COMPROBAR RESULTADO
--24 VISUALIZA LOS DISTINTOS FORMATOS DE PELICULAS
SELECT DISTINCT FORMATO
FROM PELICULAS;
--25 VISUALIZA LOS TITULOS DE PELICULAS QUE NO ESTAN NI EN DVD NI EN MP4
SELECT TITULO,
  FORMATO
FROM PELICULAS
WHERE FORMATO NOT IN ('MP4', 'DVD');
--26 TITULO DE LAS PELICULAS ESPAï¿½OLAS
SELECT TITULO
FROM PELICULAS
WHERE C_PAIS =
  (SELECT C_PAIS FROM PAISES WHERE NOMBRE_PAIS = 'Espaï¿½a'
  );
SELECT TITULO FROM PELICULAS WHERE C_PAIS = 1;
--27 NOMBRE DE LOS SOCIOS QUE NO HAN ALQUILADO NINGUNA PELICULA
SELECT NOMBRE,
  C_SOCIO
FROM SOCIOS
WHERE C_SOCIO NOT IN
  (SELECT C_SOCIO FROM ALQUILER
  );
--28 TITULO DE LAS PELICULAS QUE SE HAN ALQUILADO ALGUNA VEZ
SELECT TITULO
FROM PELICULAS
WHERE C_PELI IN
  (SELECT C_PELI FROM ALQUILER
  );
--29 ï¿½CUANTAS VECES HA ALQUILADO ROSA?
SELECT COUNT(*)
FROM ALQUILER
WHERE C_SOCIO =
  (SELECT C_SOCIO FROM SOCIOS WHERE NOMBRE = 'rosa'
  );
--30 ï¿½CUANTAS VECES SE HA ALQUILADO TORRENTE?
SELECT COUNT(*)
FROM ALQUILER
WHERE C_PELI IN
  (SELECT C_PELI FROM PELICULAS WHERE TITULO LIKE 'Torrente%'
  );
--31 NOMBRE DE LOS PAISES QUE NO HAN REALIZADO PELICULAS
SELECT NOMBRE_PAIS
FROM PAISES
WHERE C_PAIS NOT IN
  (SELECT C_PAIS FROM PELICULAS
  );
--32 NOMBRE DE LOS SOCIOS QUE VIVEN EN LA CALLE SOL
SELECT NOMBRE
FROM SOCIOS
WHERE UPPER(DIRECCION) LIKE 'SOL%';
-- USAR UPPER OR LOWER (CASE) CUANDO
--NO SABES SI LA CADENA ESTA EN MINUSCULAS O MAYUSCULAS
--33 NOMBRE DE LOS SOCIOS QUE HAN VISTO LA PELICULA 'Viven'
SELECT NOMBRE
FROM SOCIOS
WHERE C_SOCIO IN
  (SELECT C_SOCIO
  FROM ALQUILER
  WHERE C_PELI =
    (SELECT C_PELI FROM PELICULAS WHERE TITULO = 'Viven'
    )
  );
--34 NOMBRE DE LOS PAISES EN LOS QUE SE ALQUILAN PELICULAS
SELECT NOMBRE_PAIS,
  C_PAIS
FROM PAISES
WHERE C_PAIS IN
  (SELECT C_PAIS FROM PELICULAS WHERE C_PAIS IN
    (SELECT C_PAIS FROM ALQUILER
    )
  );
--35 NOMBRE DE LOS SOCIOS QUE NO HAN VISTO TORRENTE
SELECT NOMBRE
FROM SOCIOS
WHERE C_SOCIO NOT IN
  (SELECT C_SOCIO
  FROM ALQUILER
  WHERE C_PELI IN
    (SELECT C_PELI FROM PELICULAS WHERE TITULO LIKE 'Torrente%'
    )
  );
--36 NOMBRE DE LOS SOCIOS QUE NO HAN ALQUILADO PELICULAS ESPAï¿½OLAS
SELECT NOMBRE
FROM SOCIOS
WHERE C_SOCIO NOT IN
  (SELECT C_SOCIO
  FROM ALQUILER
  WHERE C_PELI IN
    (SELECT C_PELI
    FROM PELICULAS
    WHERE C_PAIS IN
      (SELECT C_PAIS FROM PAISES WHERE NOMBRE_PAIS = 'Espaï¿½a'
      )
    )
  );
--37 NOMBRE DE LOS SOCIOS QUE VEN PELICULAS QUE NO SON ESPAï¿½OLAS
SELECT NOMBRE
FROM SOCIOS
WHERE C_SOCIO IN
  (SELECT C_SOCIO
  FROM ALQUILER
  WHERE C_PELI IN
    (SELECT C_PELI
    FROM PELICULAS
    WHERE C_PAIS IN
      (SELECT C_PAIS FROM PAISES WHERE NOMBRE_PAIS != 'Espaï¿½a'
      )
    )
  );
--38 VISUALIZA CUANTS PELICULAS SE HAN EREALIZADO EN LOS DISTINTOS Aï¿½OS
SELECT ANNO,
  COUNT(C_PELI)
FROM PELICULAS
GROUP BY ANNO
ORDER BY ANNO;
--39 PRECIO MINIMO DE CADA FORMATO
SELECT FORMATO,
  MIN(PRECIO),
  COUNT(*)
FROM PELICULAS
GROUP BY FORMATO;
--40 VISUALIZA CUANTAS PELICULAS SE HAN ALQUILADO EN LOS DISTINTOS Aï¿½OS
SELECT '20'
  ||SUBSTR(FECHA, 7, 2),
  COUNT(*)
FROM ALQUILER
GROUP BY '20'
  ||SUBSTR(FECHA, 7, 2);
--41 ï¿½CUANTOS ALQUILERES SE HICIERON EN MARZO DEL 2002?
SELECT COUNT(*)
FROM ALQUILER
WHERE FECHA LIKE '%03/02';
--42 ï¿½CUANTOS HERMANOS TIENE ROSA RODRIGUEZ NIETO?
SELECT COUNT(*)-1
FROM SOCIOS
WHERE APE1 = 'rodriguez'
AND APE2   = 'nieto';
--43 VISUALIZA LOS TITULOS DE LAS PELICULAS
--   JUNTO CON EL NOMBRE DEL PAIS QUE LAS HA REALIZADO
SELECT TITULO,
  NOMBRE_PAIS
FROM PELICULAS,
  PAISES
WHERE PELICULAS.C_PAIS = PAISES.C_PAIS;
--44 VISUALIZA UN LISTADO CON NOMBRE DE LOS SOCIOS JUNTO CON LOS CODIGOS
--   DE PELICULAS QUE HA ALQUILADO CADA UNO
SELECT NOMBRE,
  C_PELI
FROM SOCIOS,
  ALQUILER
WHERE SOCIOS.C_SOCIO = ALQUILER.C_SOCIO;
-- 45 VISUALIZA LOS TITULOS DE LAS PELIS JUNTO CON EL CODIGO DE LOS SOCIOS
--    QUE LA HAN ALQUILADO
SELECT TITULO,
  C_SOCIO
FROM PELICULAS,
  ALQUILER
WHERE PELICULAS.C_PELI = ALQUILER.C_PELI;
-- 46 VISUALIZA LOS NOMBRES DE LOS PAISES JUNTO CON EL TITULO DE SUS PELICULAS
--    QUE SE HAN ALQUILADO
SELECT DISTINCT NOMBRE_PAIS,
  TITULO
FROM PAISES,
  PELICULAS,
  ALQUILER
WHERE PAISES.C_PAIS  = PELICULAS.C_PAIS
AND PELICULAS.C_PELI = ALQUILER.C_PELI;
SELECT NOMBRE_PAIS,
  TITULO
FROM PAISES,
  PELICULAS
WHERE PAISES.C_PAIS   = PELICULAS.C_PAIS
AND PELICULAS.C_PELI IN
  (SELECT C_PELI FROM ALQUILER
  );
-- 47 VISUALIZA LOS NOMBRES DE LOS SOCIOS JUNTO CON EL TITULO DE LAS PELICULAS
--    QUE HA ALQUILADO CADA UNO
SELECT NOMBRE,
  TITULO
FROM SOCIOS,
  PELICULAS,
  ALQUILER
WHERE PELICULAS.C_PELI = ALQUILER.C_PELI
AND SOCIOS.C_SOCIO     = ALQUILER.C_SOCIO;
-- 48 ï¿½CUANTAS PELICULAS ESPAï¿½OLAS HA ALQUILADO ROSA?
SELECT COUNT(*)
FROM PELICULAS
WHERE C_PAIS =
  (SELECT C_PAIS FROM PAISES WHERE NOMBRE_PAIS = 'Espaï¿½a'
  )
AND C_PELI IN
  (SELECT C_PELI
  FROM ALQUILER
  WHERE C_SOCIO =
    (SELECT C_SOCIO FROM SOCIOS WHERE NOMBRE = 'rosa'
    )
  );
-- 49 ï¿½CUANTOS DVDS FRANCESES HAY?
SELECT COUNT(*)
FROM PELICULAS
WHERE FORMATO = 'DVD'
AND C_PAIS    =
  (SELECT C_PAIS FROM PAISES WHERE NOMBRE_PAIS = 'Francia'
  );
-- 50 LISTADO CON LOS NOMBRES DE LOS PAISES JUNTO CON LOS Aï¿½OS
--    EN QUE HAN REALIZADO PELICULAS
SELECT DISTINCT NOMBRE_PAIS,
  ANNO
FROM PAISES PA,
  PELICULAS PE
WHERE PA.C_PAIS = PE.C_PAIS
ORDER BY NOMBRE_PAIS,
  ANNO;
--51 LISTADO CON TODOS LOS NOMBRES DE LOS PAISES JUNTO CON
--   EL NUMERO DE PELICULAS REALIZADAS
SELECT NOMBRE_PAIS,
  COUNT(*)
FROM PAISES PA,
  PELICULAS PE
WHERE PA.C_PAIS = PE.C_PAIS
GROUP BY NOMBRE_PAIS;
-- 52 NOMBRE DE LOS CLIENTES QUE NO SON NI DE MADRID NI DE SEVILLA
SELECT NOMBRE
FROM CLIENTE
WHERE CIUDAD NOT IN ('MADRID', 'SEVILLA');
-- 53 NOMBRE DE LOS CLIENTES QUE NO HAN REALIZADO PEDIDOS
SELECT NOMBRE
FROM CLIENTE
WHERE IDCLI NOT IN
  (SELECT IDCLI FROM PEDIDO
  );
-- 54 Â¿CUANTOS SOCIOS VIVEN EN SOL?
SELECT COUNT(*)
FROM CLIENTE
WHERE UPPER(DIREC) LIKE 'SOL%';
-- 55 NOMBRE DE LOS SOCIOS QUE NOS COMPRARON EN 2017
SELECT NOMBRE
FROM CLIENTE
WHERE IDCLI IN
  (SELECT IDCLI FROM PEDIDO WHERE FPED LIKE '%/%/17'
  );
-- 56 Â¿CUANTOS PEDIDOS NOS HA REALIZADO MARIA PEREZ?
SELECT COUNT(*)
FROM PEDIDO
WHERE IDCLI =
  (SELECT IDCLI FROM CLIENTE WHERE UPPER(NOMBRE) = 'MARIA PEREZ'
  );
-- 57 LISTADO DE ARTICULOS QUE NO SE VENDEN
SELECT DESCRIP
FROM ARTICULO
WHERE IDART NOT IN
  (SELECT IDART FROM DETALLE
  );
-- 58 LISTADO CON EL CODIGO DE CLIENTE JUNTO CON CUANTOS PEDIDOS HAN REALIZADO
SELECT IDCLI,
  COUNT(IDPED)
FROM PEDIDO
GROUP BY IDCLI;
-- 59 LISTADO CON EL CODIGO DE ARTICULO Y CUANTOS SE HAN VENDIDO
SELECT IDART,
  SUM(CANTIDAD)
FROM DETALLE
GROUP BY IDART;
-- 60 NOMBRE DEL CLIENTE QUE MAS CREDITO TIENE
SELECT NOMBRE
FROM CLIENTE
WHERE CREDIT =
  (SELECT MAX(CREDIT) FROM CLIENTE
  );
-- 61 NOMBRE DE LOS CLIENTES JUNTO CON EL NUMERO DE PEDIDOS QUE HAN REALIZADO
SELECT NOMBRE,
  COUNT(IDPED)
FROM CLIENTE C,
  PEDIDO P
WHERE C.IDCLI = P.IDCLI
GROUP BY C.NOMBRE;
-- 62 DESCRIPCION DE LOS ARTICULOS DE LOS QUE HEMOS VENDIDO MAS DE 10 UNIDADES
SELECT DESCRIP
FROM ARTICULO
WHERE IDART =
  (SELECT IDART FROM DETALLE WHERE CANTIDAD > 10
  );
-- 63 DESCRIPCION DE LOS ARTICULOS DE LOS QUE TENEMOS UN STOCK BAJO (< 250)
SELECT DESCRIP
FROM ARTICULO
WHERE STOCK < 250;
-- 64 ¿QUIEN COMPRA SALCHICHAS?
SELECT NOMBRE
FROM CLIENTE
WHERE IDCLI =
  (SELECT IDCLI
  FROM PEDIDO
  WHERE IDPED =
    (SELECT IDPED
    FROM DETALLE
    WHERE IDART =
      (SELECT IDART FROM ARTICULO WHERE DESCRIP = 'SALCHICHAS'
      )
    )
  );
-- 65 LISTADO DE LOS DISTINTOS FORMATOS JUNTO CON CUANTAS PELIS HAY DE CADA
SELECT FORMATO,
  COUNT(*)
FROM PELICULAS
GROUP BY FORMATO;
-- 66 LISTADO CON TODOS LOS TITULOS DE LAS PELICULAS JUNTO CON EL NUMERO DE ALQUILERES DE ESA PELICULA
SELECT TITULO,
  COUNT(A.C_PELI)
FROM PELICULAS P,
  ALQUILER A
WHERE P.C_PELI = A.C_PELI(+)
GROUP BY TITULO;
-- 67 VISUALIZAR EL NOMBRE DE LOS PAISES QUE HAN REALIZADO MAS DE 2 PELICULAS
SELECT NOMBRE_PAIS
FROM PAISES
WHERE C_PAIS IN
  (SELECT C_PAIS FROM PELICULAS GROUP BY C_PAIS HAVING COUNT(*) > 2
  );
-- 68 ¿EN QUE FORMATOS TENEMOS MAS DE 6 PELICULAS?
SELECT FORMATO,
  COUNT(*)
FROM PELICULAS
GROUP BY FORMATO
HAVING COUNT(*) > 6;
-- 69 ¿CUAL ES EL FORMATO MÁS FRECUENTE?
SELECT FORMATO
FROM PELICULAS
GROUP BY FORMATO
HAVING COUNT(*) =
  (SELECT MAX(COUNT(*)) FROM PELICULAS GROUP BY FORMATO
  );
-- 70 ¿CUAL ES EL AÑO EN EL QUE SE REALIZARON MÁS PELICULAS?
SELECT ANNO
FROM PELICULAS
GROUP BY ANNO
HAVING COUNT(*) =
  (SELECT MAX(COUNT(*)) FROM PELICULAS GROUP BY ANNO
  );
-- 71 ¿CUAL ES EL PAIS QUE MAS CINES TIENE?
SELECT NOMBRE_PAIS
FROM PAISES
WHERE CINES =
  (SELECT MAX(CINES) FROM PAISES
  );
-- 72 ¿EN QUE AÑO SE ALQUILARON MAS PELICULAS?
SELECT CONCAT('20',SUBSTR(FECHA, 7, 2))
FROM ALQUILER
GROUP BY SUBSTR(FECHA, 7, 2)
HAVING COUNT(*) =
  (SELECT MAX(COUNT(*)) FROM ALQUILER GROUP BY SUBSTR(FECHA, 7, 2)
  );
-- 73 ¿CUAL ES LA PELICULA QUE MAS SE ALQUILA?
SELECT TITULO
FROM PELICULAS
WHERE C_PELI IN
  (SELECT C_PELI
  FROM ALQUILER
  GROUP BY C_PELI
  HAVING COUNT(*) =
    (SELECT MAX(COUNT(*)) FROM ALQUILER GROUP BY C_PELI
    )
  );
-- 74 NOMBRE DEL SOCIO QUE MAS PELICULAS HA ALQUILADO
SELECT NOMBRE
FROM SOCIOS
WHERE C_SOCIO IN
  (SELECT C_SOCIO
  FROM ALQUILER
  GROUP BY C_SOCIO
  HAVING COUNT(*) =
    (SELECT MAX(COUNT(*)) FROM ALQUILER GROUP BY C_SOCIO
    )
  );
-- 75 NOMBRE DE LOS SOCIOS QUE NO VEN PELICULAS ESPAÑOLAS
SELECT NOMBRE
FROM SOCIOS
WHERE C_SOCIO NOT IN
  (SELECT C_SOCIO
  FROM ALQUILER
  WHERE C_PELI IN
    (SELECT C_PELI
    FROM PELICULAS
    WHERE C_PAIS IN
      (SELECT C_PAIS FROM PAISES WHERE NOMBRE_PAIS = 'España'
      )
    )
  );
-- 76 NOMBRE DE LOS SOCIOS QUE TIENEN HERMANOS
SELECT NOMBRE
FROM SOCIOS
WHERE (APE1, APE2) IN
  (SELECT APE1, APE2 FROM SOCIOS GROUP BY APE1, APE2 HAVING COUNT(*) > 1
  );
SELECT NOMBRE
FROM SOCIOS
WHERE (APE1, APE2) IN
  (SELECT APE1, APE2 FROM SOCIOS SO WHERE SOCIOS.NOMBRE != SO.NOMBRE
  );
-- 77 ¿QUE PAISES NO ALQUILAN SUS PELICULAS?
SELECT NOMBRE_PAIS
FROM PAISES
WHERE C_PAIS NOT IN
  (SELECT C_PAIS FROM PELICULAS WHERE C_PELI IN
    (SELECT C_PELI FROM ALQUILER
    )
  );
-- 78 ¿CON QUE PELICULAS HEMOS GANADO MAS DINERO?
SELECT TITULO
FROM PELICULAS
WHERE C_PELI IN
  (SELECT C_PELI
  FROM ALQUILER
  GROUP BY C_PELI
  HAVING SUM(TOTAL) =
    (SELECT MAX(SUM(TOTAL)) FROM ALQUILER GROUP BY C_PELI
    )
  );
-- 79 ¿CUANTO SE HA FACTURADO CON LAS PELICULAS ESPAÑOLAS?
SELECT SUM(SUM(TOTAL))
FROM ALQUILER
GROUP BY C_PELI
HAVING C_PELI IN
  (SELECT C_PELI
  FROM PELICULAS
  WHERE C_PAIS =
    (SELECT C_PAIS FROM PAISES WHERE NOMBRE_PAIS = 'España'
    )
  );
-- 80 VISUALIZA LOS NOMBRES DE LOS PAISES QUE NO TIENEN NINGUN ALQUILER
SELECT NOMBRE_PAIS
FROM PAISES
WHERE C_PAIS NOT IN
  (SELECT C_PAIS FROM PELICULAS WHERE C_PELI IN
    (SELECT C_PELI FROM ALQUILER
    )
  );
-- 81 NOMBRE DE LOS SOCIOS QUE SON DE MADRID O DE TOLEDO (POR SUS TELEFONOS)
SELECT NOMBRE AS MADRID_Y_TOLEDO
FROM SOCIOS
WHERE TELEFONO LIKE '91%'
UNION
SELECT NOMBRE FROM SOCIOS WHERE TELEFONO LIKE '925%';
-- 82 NOMBRE Y APELLIDOS DE LOS SOCIOS QUE DE PRIMER APELLIDO NO SIN NI RAMIREZ NI RODRIGUEZ
SELECT NOMBRE,APE1,APE2 FROM SOCIOS WHERE APE1 NOT LIKE 'RAMIREZ' INTERSECT SELECT NOMBRE,APE1,APE2 FROM SOCIOS WHERE APE1 NOT LIKE 'RODRIGUEZ';

-- 83 NOMBRE DE LOS SOCIOS QUE NO REALIZAN MAS DE 2 ALQUILERES
SELECT NOMBRE FROM SOCIOS  WHERE C_SOCIO NOT IN (SELECT C_SOCIO FROM ALQUILER GROUP BY C_SOCIO HAVING COUNT(*)>2);
-- 84 ¿CUANTAS PELICULAS TIENEN LOS RODRIGUEZ EN SU CASA?
SELECT COUNT(*) FROM ALQUILER WHERE DEVUELTA = 'N' AND C_SOCIO IN 
(SELECT C_SOCIO FROM SOCIOS WHERE APE1 = 'rodriguez');
-- 85 ¿QUE PELIS NO SE PUEDEN ALQUILAR PORQUE ESTAN EN CASA DE ALGUIEN?
SELECT TITULO,C_PELI FROM PELICULAS WHERE C_PELI IN
(SELECT C_PELI FROM ALQUILER WHERE DEVUELTA = 'N');
-- 86 NOMBRE DE LOS CLIENTES QUE NO NOS COMPRAN
SELECT NOMBRE FROM CLIENTES WHERE C_CLIENTE NOT IN 
(SELECT C_CLIENTE FROM VENTAS);
-- 87 NOMBRE DE LOS CLIENTES QUE NOS HAN COMPRADO RAQUETAS
SELECT NOMBRE FROM CLIENTES WHERE C_CLIENTE IN
(SELECT C_CLIENTE FROM VENTAS WHERE C_ART =
(SELECT C_ART FROM ARTICULO WHERE DESCRIP = 'raqueta'));
-- 88 ¿CUANTO HEMOS FACTURADO EN EL 2017?
SELECT SUM(CANTIDAD * PRECIO) FROM VENTAS,ARTICULO WHERE VENTAS.C_ART = ARTICULO.C_ART AND SUBSTR(FECHA, 7, 2) = '17' ORDER BY DESCRIP;
-- 89 DE QUE ARTICULOS TENEMOS MAS UNIDADES EN LA TIENDA?
SELECT DESCRIP FROM ARTICULO WHERE STOCK IN 
(SELECT MAX(STOCK) FROM ARTICULO);